// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu3Vb8PMTLtyeoNH_uYXG68lAiwhwBdV8',
    appId: '1:112561895353:web:b147e1c82d754c0430e868',
    messagingSenderId: '112561895353',
    projectId: 'fixmate-9e1fa',
    authDomain: 'fixmate-9e1fa.firebaseapp.com',
    storageBucket: 'fixmate-9e1fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwu5zwoy9arBK0v-FnJbN76vbkVFlu3nM',
    appId: '1:112561895353:android:3804b82d3baea03030e868',
    messagingSenderId: '112561895353',
    projectId: 'fixmate-9e1fa',
    storageBucket: 'fixmate-9e1fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9YgDk3fENakfwOBqO8awFzcsMpvDdEuo',
    appId: '1:112561895353:ios:9e3241483370a21130e868',
    messagingSenderId: '112561895353',
    projectId: 'fixmate-9e1fa',
    storageBucket: 'fixmate-9e1fa.firebasestorage.app',
    iosBundleId: 'com.example.fixmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9YgDk3fENakfwOBqO8awFzcsMpvDdEuo',
    appId: '1:112561895353:ios:9e3241483370a21130e868',
    messagingSenderId: '112561895353',
    projectId: 'fixmate-9e1fa',
    storageBucket: 'fixmate-9e1fa.firebasestorage.app',
    iosBundleId: 'com.example.fixmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu3Vb8PMTLtyeoNH_uYXG68lAiwhwBdV8',
    appId: '1:112561895353:web:8a425401e13f55c130e868',
    messagingSenderId: '112561895353',
    projectId: 'fixmate-9e1fa',
    authDomain: 'fixmate-9e1fa.firebaseapp.com',
    storageBucket: 'fixmate-9e1fa.firebasestorage.app',
  );
}
